release:
  name: Create GitHub Release
  needs: build
  runs-on: ubuntu-latest

  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: doris-executable
        path: dist/

    - name: Create a Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/doris
        tag_name: v1.0.0
        release_name: "Doris v1.0.0"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
